name: âœ¨ Add epics to Roadmap âœ¨

on:
  issues:
    types: [opened, edited, labeled, assigned]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: ðŸŽ¯ Move to Wish List ðŸŽ¯
    steps:
    - name: Assign issues with `user-story` label to project 3
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'user-story')
      with:
        project: 'https://github.com/orgs/KaotoIO/projects/3'
        column_name: 'WishList'
        
  assign_to_Kaoto_private:
    runs-on: ubuntu-latest
    name: ðŸŽ¯ Move to Kaoto List ðŸŽ¯
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/KaotoIO/projects/10
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}

  assign_to_newcomers_list:
    runs-on: ubuntu-latest
    name: ðŸŽ¯ Move to Newcomers List ðŸŽ¯
    steps:
    - name: Assign issues with `good first issue` label to project 4
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'good first issue')
      with:
        project: 'https://github.com/orgs/KaotoIO/projects/4'
        column_name: 'What To Do'
    - name: Assign issues with `help wanted` label to project 4
      uses: srggrs/assign-one-project-github-action@1.3.1
      if: contains(github.event.issue.labels.*.name, 'help wanted')
      with:
        project: 'https://github.com/orgs/KaotoIO/projects/4'
        column_name: 'What To Do'
